// <auto-generated />
using BestPhoneNumber.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BestPhoneNumber.Migrations
{
    [DbContext(typeof(PhoneContext))]
    partial class PhoneContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BestPhoneNumber.Models.NumberProvide", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("PrefixNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TelecomHostId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("NumberProvide");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PrefixNumber = "086",
                            TelecomHostId = 1
                        },
                        new
                        {
                            Id = 2,
                            PrefixNumber = "096",
                            TelecomHostId = 1
                        },
                        new
                        {
                            Id = 3,
                            PrefixNumber = "097",
                            TelecomHostId = 1
                        },
                        new
                        {
                            Id = 4,
                            PrefixNumber = "089",
                            TelecomHostId = 2
                        },
                        new
                        {
                            Id = 5,
                            PrefixNumber = "090",
                            TelecomHostId = 2
                        },
                        new
                        {
                            Id = 6,
                            PrefixNumber = "093",
                            TelecomHostId = 2
                        },
                        new
                        {
                            Id = 7,
                            PrefixNumber = "088",
                            TelecomHostId = 3
                        },
                        new
                        {
                            Id = 8,
                            PrefixNumber = "091",
                            TelecomHostId = 3
                        },
                        new
                        {
                            Id = 9,
                            PrefixNumber = "094",
                            TelecomHostId = 3
                        });
                });

            modelBuilder.Entity("BestPhoneNumber.Models.TelecomHost", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TelecomHost");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Viettel"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Mobi"
                        },
                        new
                        {
                            Id = 3,
                            Name = "VinaPhone"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
